### PR TITLE
feat: evaluate .ignore files during the change detection process

### PR DESCRIPTION
**Pull request by philippwaller**
**What this PR does / why we need it**:
This PR adds the ability to exclude files during the change detection process. This can be particularly useful in the context of version increment checks. If the feature is enabled, all `.ctignore` and `.helmignore` files inside the configured chart directories are evaluated by default and applied relative to the file path. All common glob patterns, including the globstar pattern `**`, are supported. In addition, the configuration parameter `considered-dotignore-files` can be adjusted to specify which `.ignore` files are to be considered.

Added config parameters (default values):
```yaml
evaluate-dotignore-files: false
considered-dotignore-files:
    - .ctignore
    - .helmignore
```

**Special notes for your reviewer**: I added/modified test cases to cover the new functionality.

Signed-off-by: Philipp Waller <1090452+philippwaller@users.noreply.github.com>

### CODE REVIEW

**Comment by philippwaller** [comment]
Dear Core Team,
do you have any feedback or change request regarding this PR? Thanks!

**Comment by johanneskastl** [comment]
Any updates on this? I would like to see this functionality, but seems like there was no reaction from the maintainers?

**Comment by philippwaller** [comment]
I would be happy to revise the PR if the code is considered for future releases. Just let me know and I will make the necessary changes to ensure that the code is ready for integration.

**Comment by cpanato** [comment]
This looks good, can we rebase and get this PR up-to-date, so we can run some manual tests? also will be good if you have a sample ci pipeline to show this working 

thanks for working on this

**Comment by mavimo** [comment]
@philippwaller if you need support ping me, I'm available for testing, code review or any other think that can be useful 🙈

**Comment by lhriley** [comment]
Any updates on this work? It would be great to see this feature merged. 🥇

**Comment by philippwaller** [comment]
I will update this PR by end of next week. ✌️

**Pull request closed without merging**
