### PR TITLE
chart_schema.yaml - dependency.repository should not be required

### PR DESCRIPTION
**Pull request by itewk**
**What this PR does / why we need it**:

Makes the depednecy.*.repository field optional because when using a local chart there is no repository.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by krtk6160** [comment]
@unguiculus @cpanato Can this be merged? By having the repository field as mandatory, subcharts developed locally cannot be tested. Related #324

**Review by cpanato — CHANGES_REQUESTED** [review]
in general LGTM

can you please sign the DCO and rebase your PR?

**Comment by itewk** [comment]
@cpanato done.

**Review by unguiculus — APPROVED** [review]

**Review by cpanato — APPROVED** [review]

**Comment by itewk** [comment]
@cpanato thank you

**Comment by krtk6160** [comment]
Any ETA on when this'll be part of a release? I assume v3.3.2 will include this?

**Comment by cpanato** [comment]
I will take a look next week

**Comment by tanmay7270** [comment]
Any update on the release? Our subchart testing jobs have been failing due to this.

**Pull request merged**
