### PR TITLE
--chart-repos help message improvement

### PR DESCRIPTION
**Pull request by depohmel**
**What this PR does / why we need it**:
pkg/chart/chart.go:201 is expecting repo to be name=url
this PR is just making help message clear

### CODE REVIEW

**Comment by unguiculus** [comment]
@depohmel I fixed conflicts but you'll still have to sign off your commits.

See https://github.com/helm/chart-testing/pull/74/checks?check_run_id=47152328

**Comment by depohmel** [comment]
@unguiculus it looks like GitHub doesn't like this one: https://github.com/helm/chart-testing/pull/74/commits/9577b987b81ef77ddba150247dac6f4ab5d05a33 
Should I manually fix @kunickiaj in signed off?

**Comment by unguiculus** [comment]
Something went wrong here. Can you just rebase and remove this commit? It's already on master anyways.

**Comment by depohmel** [comment]
@unguiculus sorry I forced pushed master branch into this one and this closed this PR. I just open a new one. https://github.com/helm/chart-testing/pull/82

Sorry about it :(

**Pull request closed without merging**
