### PR TITLE
Reduce Docker Image Size

### PR DESCRIPTION
**Pull request by philoserf**
Size

- use the _builder_ pattern
- use the _RUN ... \ && ..._ pattern
- use _COPY item1 item2 ... destination_ pattern
- use a python/alpine image rather than installing python, etc
- remove apk packages that are not required
- remove cache/control file from final image layer

Other Changes

- use cURL flags -sLo to improve output and control local file names

Signed-off-by: Mark Ayers <mark@philoserf.com>

### CODE REVIEW

**Comment by philoserf** [comment]
FWIW: v2.0.1 was 207MB This is 175MB. It should also be a bit faster at build time.

**Comment by philoserf** [comment]
It occurred to mean as I slept that perhaps `git` was used in the `ct` workflow. Taking a closer look at how the tool is used.

**Comment by unguiculus** [comment]
Thanks for your contribution. What makes you think some packages are no required? If you add them back you probably won't save anything by restructuring the Dockerfile. I don't think it make sense to use a multi-stage docker build here. The original Dockerfile is IMO clearer and better to understand.

**Comment by philoserf** [comment]
It is easier to read. Granted.

Size, layer count, and speed can matter. I propose here some of Docker’s own best practices for Dockerfiles.

**Comment by philoserf** [comment]
BTW. I took a look into the image with `dive`. This lead me to some of the size savings. 

Ref: https://github.com/wagoodman/dive/blob/master/README.md

**Pull request closed without merging**
