### PR TITLE
extraArgs removed from uninstall command

### LINKED ISSUE #212: unknown flag when chart uninstalled
BUG REPORT

ct version 3.0.0-beta2

**What happened**:
```
ct lint-and-install --chart-dirs $(pwd) --validate-maintainers=false --helm-extra-args="--values redis/ci/vault-values.yaml" --charts redis  --debug

...
Deleting release 'redis-5xuikf4s43'...
>>> helm uninstall redis-5xuikf4s43 --namespace redis-5xuikf4s43 --values redis/ci/vault-values.yaml
Error: unknown flag: --values
Error deleting Helm release: Error waiting for process: exit status 1
Deleting namespace 'redis-5xuikf4s43'...
>>> kubectl delete namespace redis-5xuikf4s43 --timeout 180s
namespace "redis-5xuikf4s43" deleted
>>> kubectl get namespace redis-5xuikf4s43
Namespace 'redis-5xuikf4s43' terminated.
Error: Error linting and installing charts: Error processing charts
```

i think extra args must not be present in uninstall part.

### PR DESCRIPTION
**Pull request by ahmetkaftan**
Signed-off-by: Ahmet Kaftan <ahmet.kaftan@cloudnesil.com>

**What this PR does / why we need it**:
When removing chart after chart install, `helm uninstall` command gets the `extraArgs` which has been added with `--helm-extra-args` flag.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #212

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by alespour** [comment]
@tylerauerbeck This would be nice to have merged. Thank you for your consideration.

**Comment by tylerauerbeck** [comment]
@alespour Thanks for the ping. This seems fairly harmless and seems to work to me. But, I don't have any approver/merge power here. So we'll probably want @cpanato or @scottrigby to take a look.

**Comment by smlx** [comment]
So with this PR how do I pass an extra argument to the `helm uninstall` command?

**Comment by ahmetkaftan** [comment]
> So with this PR how do I pass an extra argument to the `helm uninstall` command?

I don't think it's necessary to pass extra arguments when running `helm uninstall` command.

**Comment by smlx** [comment]
> I don't think it's necessary to pass extra arguments when running `helm uninstall` command.

I disagree. There are plenty of global options which might be useful being passed to `uninstall`. In addition this is a breaking change. A better solution to #212 is in a comment on that issue: https://github.com/helm/chart-testing/issues/212#issuecomment-602049793

**Comment by ahmetkaftan** [comment]
fixed with #402

**Pull request closed without merging**
