### PR TITLE
Use environment variable for Github address

### PR DESCRIPTION
**Pull request by erikasm**
Enable setting different Github address e.g. for Github Enterprise instances

### CODE REVIEW

**Comment by unguiculus** [comment]
Thanks for the PR. Please update the readme as well.

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* One or more commits are not associated with a GitHub user. The email used in the Git commit must match a verified email address in a GitHub user profile. For more information, please see https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/

_Regards,
CLA GitHub bot_

**Comment by mattfarina** [comment]
We've switched to the DCO. Details are available at https://www.helm.sh/blog/helm-dco/index.html.

Can you please sign your commits when you update. The DCO bot will show up and tell you the commands if you miss something or are unsure.

**Comment by mattfarina** [comment]
Missed the commit to update the README. This looks good. Thanks.

**Pull request merged**
