### PR TITLE
Add --force and --chart option for install and lint

### PR DESCRIPTION
**Pull request by rimusz**
Signed-off-by: rimas <rmocius@gmail.com>

### CODE REVIEW

**Comment by rimusz** [comment]
ping @unguiculus @mattfarina

**Comment by unguiculus** [comment]
The question is if such things should be additional flags or go into the configuration. I merged #23 first because it feels more consistent with the existing style. What do others think?

cc @helm/charts-maintainers @mattfarina

**Comment by rimusz** [comment]
I will create another PR, there will reuse #23 logic to skip the version check. Regarding extra flags I found it easier to use them for local development to kick tests quicker, but I can also include the env vars support as well.

**Comment by rimusz** [comment]
new #24 replaces this one, closing

**Pull request closed without merging**
