### PR TITLE
Introduce helm-extra-set-args command line parameter

### LINKED ISSUE #171: Ability to test with custom values file
Feature request:
add an option to pass custom values file for helm, for example:

```text
--helm-values-file custom.yaml
```
Right now using `--helm-extra-args` unfortunately is also passed to `helm test` command so adding `--values custom.yaml` ends with error because it renders `helm test .... --values custom.yaml` which returns error because `-values` is unknown option for `helm test`.

This means that  `--helm-extra-args` is actually limited to common helm parameters.

### LINKED ISSUE #212: unknown flag when chart uninstalled
BUG REPORT

ct version 3.0.0-beta2

**What happened**:
```
ct lint-and-install --chart-dirs $(pwd) --validate-maintainers=false --helm-extra-args="--values redis/ci/vault-values.yaml" --charts redis  --debug

...
Deleting release 'redis-5xuikf4s43'...
>>> helm uninstall redis-5xuikf4s43 --namespace redis-5xuikf4s43 --values redis/ci/vault-values.yaml
Error: unknown flag: --values
Error deleting Helm release: Error waiting for process: exit status 1
Deleting namespace 'redis-5xuikf4s43'...
>>> kubectl delete namespace redis-5xuikf4s43 --timeout 180s
namespace "redis-5xuikf4s43" deleted
>>> kubectl get namespace redis-5xuikf4s43
Namespace 'redis-5xuikf4s43' terminated.
Error: Error linting and installing charts: Error processing charts
```

i think extra args must not be present in uninstall part.

### LINKED ISSUE #322: ct install error while uninstalling with --helm-extra-args
**Version of Helm and Kubernetes**:
helm version: v3.4.0
kubectl version: v1.20.2
ct version:  helm/chart-testing-action@v2.0.1

**What happened**:
When using ct install with --helm-extra-args --set the uninstall of the helm chart gives an error. 
```
helm uninstall helm-chart --namespace default --set key=value
Error: Error installing charts: Error processing charts
Error: unknown flag: --set
Error deleting Helm release: Error waiting for process: exit status 1
```

**What you expected to happen**:
The expectation was that the helm chart could be uninstalled correctly. 

**How to reproduce it** (as minimally and precisely as possible):
Use ```ct install``` with an ```--helm-extra-args``` that is not available in the ```helm uninstall``` command but can be used in ```helm install```.  

**Anything else we need to know**:
I guess the issue is because the same variable is used in the following code snippets:

Uninstall: 
https://github.com/helm/chart-testing/blob/e84e88cf8bd04ac91000fd675d4cfc2ddf69ba96/pkg/tool/helm.go#L81

Install/Upgrade: 
https://github.com/helm/chart-testing/blob/e84e88cf8bd04ac91000fd675d4cfc2ddf69ba96/pkg/tool/helm.go#L58
https://github.com/helm/chart-testing/blob/e84e88cf8bd04ac91000fd675d4cfc2ddf69ba96/pkg/tool/helm.go#L67

### PR DESCRIPTION
**Pull request by ilmax**
**What this PR does / why we need it**:
Often times it's required to override the values file when running chart-testing, we have `helm-extra-args` command line option, but that one is used also to uninstall the release so adding set parameters there results in an error in uninstalling the release (see #322, #212, #171)

**Which issue this PR fixes**
fixes #322, fixes #212, fixes #171

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by cpanato** [comment]
@ilmax thanks for the PR, there are some updates in the tests you need to adjust and also can you add some tests for this change as well?

**Comment by ilmax** [comment]
@cpanato I fixed the issue, and added an integration test where I fetch another version of nginx, let me know if you need me to do something more here, Thanks!

**Comment by cpanato** [comment]
@ilmax thanks for the PR
can you generate the docs using the doc-gen?

```
go build -o ct-bin ./ct/main.go

$ ./ct-bin doc-gen
Generating docs...
Done.
```

then commit the changes?
thanks!

**Comment by ilmax** [comment]
@cpanato Sorry, I missed that, done and pushed!

**Review by cpanato — APPROVED** [review]
lgtm

**Pull request merged**
