### PR TITLE
Do not disable version check on one chart

### PR DESCRIPTION
**Pull request by RafalKorepta**
**What this PR does / why we need it**:
Because one chart in the configuration could have evaluated version check.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: none

**Special notes for your reviewer**:
Please see conversation in https://github.com/redpanda-data/helm-charts/pull/708#issuecomment-1712455752

Test output
```
$ go build -o ct-binary ./ct/main.go
$ cd ~/redpanda/helm-charts
$ ~/chart-testing/ct-binary lint --config .github/ct-operator.yaml --chart-yaml-schema /opt/homebrew/Cellar/chart-testing/3.9.0/.bottle/etc/ct/chart_schema.yaml --lint-conf /opt/homebrew/Cellar/chart-testing/3.9.0/.bottle/etc/ct/lintconf.yaml

Linting charts...
>>> helm version --template {{ .Version }}

------------------------------------------------------------------------------------------------------------------------
 Charts to be processed:
------------------------------------------------------------------------------------------------------------------------
 operator => (version: "0.3.13", path: "charts/operator")
------------------------------------------------------------------------------------------------------------------------

>>> helm repo add redpanda https://charts.redpanda.com
"redpanda" already exists with the same configuration, skipping
>>> helm dependency build charts/operator
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "jetstack" chart repository
...Successfully got an update from the "prometheus-community" chart repository
...Successfully got an update from the "redpanda" chart repository
...Successfully got an update from the "projectcalico" chart repository
Update Complete. ⎈Happy Helming!⎈
Saving 1 charts
Downloading kube-prometheus-stack from repo https://prometheus-community.github.io/helm-charts
Deleting outdated charts
Linting chart "operator => (version: \"0.3.13\", path: \"charts/operator\")"
Checking chart "operator => (version: \"0.3.13\", path: \"charts/operator\")" for a version bump...
>>> git cat-file -e origin/main:charts/operator/Chart.yaml
>>> git show origin/main:charts/operator/Chart.yaml
Old chart version: 0.3.13
New chart version: 0.3.13

------------------------------------------------------------------------------------------------------------------------
 ✖︎ operator => (version: "0.3.13", path: "charts/operator") > chart version not ok. Needs a version bump! 
------------------------------------------------------------------------------------------------------------------------
Error: failed linting charts: failed processing charts
failed linting charts: failed processing charts

```

### CODE REVIEW

**Review by alejandroEsc — APPROVED** [review]
lgtm

**Review by joejulian — APPROVED** [review]
I've never understood why this worked this way. If CheckVersionIncrement is set by the user, why override it based on the number of charts being checked?

**Comment by joejulian** [comment]
@jouve then check on those options, not on the number of charts being linted? If the necessary target-branch and repo are set, there's not reason why the version bump shouldn't be checked regardless of how many charts are being linted.

**Comment by RafalKorepta** [comment]
Maybe @davidkarlsen @cpanato?

**Pull request closed without merging**
