### PR TITLE
Update kind cluster example with working local storage for all nodes

### PR DESCRIPTION
**Pull request by rimusz**
Signed-off-by: rimas <rmocius@gmail.com>

### CODE REVIEW

**Comment by rimusz** [comment]
cc @unguiculus 
screenshot 2019-02-21 12 45 56

**Comment by rimusz** [comment]
Do not merge as [rancher/local-path-provisioner](https://github.com/rancher/local-path-provisioner) generally seems to support multi-node clusters, but volumes always seem to be mounted using `root` as group irrespective of a specified security context, so some charts testing will fail.

See https://github.com/rancher/local-path-provisioner/issues/7

**Comment by unguiculus** [comment]
Closing issue for now.

**Comment by unguiculus** [comment]
Let's give it another try. The issue in local-path-provisioner was fixed.

**Comment by unguiculus** [comment]
Still not quite there yet.

Fix coming: https://github.com/rancher/local-path-provisioner/pull/9

**Comment by cpanato** [comment]
cool! i'm using this in our tests as well

**Pull request merged**
